import { QuizQuestion, SubjectId, Language } from '../types';

export function getDefaultQuizQuestions(subject: SubjectId, language: Language): QuizQuestion[] {
  if (subject === 'math') {
    switch (language) {
      case 'en':
        return [
          {
            id: 'm1',
            topic: 'Fractions and Ratios',
            questionNumber: 1,
            totalQuestions: 3,
            questionMarathi: 'In the fraction 3/4, what is the number 3 called?',
            questionEnglish: 'In the fraction 3/4, what is the number 3 called?',
            options: [
              { key: 'A', labelMarathi: 'Numerator', labelEnglish: 'Numerator' },
              { key: 'B', labelMarathi: 'Denominator', labelEnglish: 'Denominator' },
              { key: 'C', labelMarathi: 'Quotient', labelEnglish: 'Quotient' },
              { key: 'D', labelMarathi: 'Remainder', labelEnglish: 'Remainder' },
            ],
            correctKey: 'A',
            explanationMarathi: 'The top number in a fraction is the Numerator, representing equal parts selected.',
            explanationEnglish: 'The top number in a fraction is the Numerator, representing equal parts selected.',
          },
          {
            id: 'm2',
            topic: 'Fractions and Ratios',
            questionNumber: 2,
            totalQuestions: 3,
            questionMarathi: 'What is 1/2 + 1/4 equal to?',
            questionEnglish: 'What is 1/2 + 1/4 equal to?',
            options: [
              { key: 'A', labelMarathi: '3/4', labelEnglish: '3/4' },
              { key: 'B', labelMarathi: '2/6', labelEnglish: '2/6' },
              { key: 'C', labelMarathi: '2/4', labelEnglish: '2/4' },
              { key: 'D', labelMarathi: '1/8', labelEnglish: '1/8' },
            ],
            correctKey: 'A',
            explanationMarathi: 'Convert 1/2 to 2/4, then add 2/4 + 1/4 = 3/4.',
            explanationEnglish: 'Convert 1/2 to 2/4, then add 2/4 + 1/4 = 3/4.',
          },
          {
            id: 'm3',
            topic: 'Fractions and Ratios',
            questionNumber: 3,
            totalQuestions: 3,
            questionMarathi: 'If a class has 15 boys and 10 girls, what is the simplified ratio of boys to girls?',
            questionEnglish: 'If a class has 15 boys and 10 girls, what is the simplified ratio of boys to girls?',
            options: [
              { key: 'A', labelMarathi: '3:2', labelEnglish: '3:2' },
              { key: 'B', labelMarathi: '2:3', labelEnglish: '2:3' },
              { key: 'C', labelMarathi: '15:10', labelEnglish: '15:10' },
              { key: 'D', labelMarathi: '5:2', labelEnglish: '5:2' },
            ],
            correctKey: 'A',
            explanationMarathi: 'Dividing both numbers by 5 gives 15÷5 = 3 and 10÷5 = 2, so the ratio is 3:2.',
            explanationEnglish: 'Dividing both numbers by 5 gives 15÷5 = 3 and 10÷5 = 2, so the ratio is 3:2.',
          },
        ];
      case 'hi':
        return [
          {
            id: 'm1',
            topic: 'Fractions and Ratios',
            questionNumber: 1,
            totalQuestions: 3,
            questionMarathi: 'भिन्न 3/4 में संख्या 3 को क्या कहा जाता है?',
            questionEnglish: 'In the fraction 3/4, what is the number 3 called?',
            options: [
              { key: 'A', labelMarathi: 'अंश (Numerator)', labelEnglish: 'Numerator' },
              { key: 'B', labelMarathi: 'हर (Denominator)', labelEnglish: 'Denominator' },
              { key: 'C', labelMarathi: 'भागफल (Quotient)', labelEnglish: 'Quotient' },
              { key: 'D', labelMarathi: 'शेषफल (Remainder)', labelEnglish: 'Remainder' },
            ],
            correctKey: 'A',
            explanationMarathi: 'भिन्न में ऊपर की संख्या को अंश (Numerator) कहते हैं।',
            explanationEnglish: 'The top number in a fraction is the Numerator.',
          },
          {
            id: 'm2',
            topic: 'Fractions and Ratios',
            questionNumber: 2,
            totalQuestions: 3,
            questionMarathi: '1/2 + 1/4 का मान क्या होगा?',
            questionEnglish: 'What is 1/2 + 1/4 equal to?',
            options: [
              { key: 'A', labelMarathi: '3/4', labelEnglish: '3/4' },
              { key: 'B', labelMarathi: '2/6', labelEnglish: '2/6' },
              { key: 'C', labelMarathi: '2/4', labelEnglish: '2/4' },
              { key: 'D', labelMarathi: '1/8', labelEnglish: '1/8' },
            ],
            correctKey: 'A',
            explanationMarathi: '1/2 को 2/4 में बदलें, फिर 2/4 + 1/4 = 3/4.',
            explanationEnglish: 'Convert 1/2 to 2/4, then add 2/4 + 1/4 = 3/4.',
          },
          {
            id: 'm3',
            topic: 'Fractions and Ratios',
            questionNumber: 3,
            totalQuestions: 3,
            questionMarathi: 'यदि एक कक्षा में 15 लड़के और 10 लड़कियाँ हैं, तो लड़कों और लड़कियों का अनुपात क्या है?',
            questionEnglish: 'If a class has 15 boys and 10 girls, what is the ratio of boys to girls?',
            options: [
              { key: 'A', labelMarathi: '3:2', labelEnglish: '3:2' },
              { key: 'B', labelMarathi: '2:3', labelEnglish: '2:3' },
              { key: 'C', labelMarathi: '15:10', labelEnglish: '15:10' },
              { key: 'D', labelMarathi: '5:2', labelEnglish: '5:2' },
            ],
            correctKey: 'A',
            explanationMarathi: 'दोनों संख्याओं को 5 से विभाजित करने पर 3:2 अनुपात प्राप्त होता है।',
            explanationEnglish: 'Dividing both numbers by 5 gives a 3:2 ratio.',
          },
        ];
      case 'gu':
        return [
          {
            id: 'm1',
            topic: 'Fractions and Ratios',
            questionNumber: 1,
            totalQuestions: 3,
            questionMarathi: 'અપૂર્ણાંક 3/4 માં સંખ્યા 3 ને શું કહેવાય?',
            questionEnglish: 'In the fraction 3/4, what is the number 3 called?',
            options: [
              { key: 'A', labelMarathi: 'અંશ (Numerator)', labelEnglish: 'Numerator' },
              { key: 'B', labelMarathi: 'છેદ (Denominator)', labelEnglish: 'Denominator' },
              { key: 'C', labelMarathi: 'ભાગફળ (Quotient)', labelEnglish: 'Quotient' },
              { key: 'D', labelMarathi: 'શેષ (Remainder)', labelEnglish: 'Remainder' },
            ],
            correctKey: 'A',
            explanationMarathi: 'અપૂર્ણાંકમાં ઉપરની સંખ્યાને અંશ (Numerator) કહેવામાં આવે છે.',
            explanationEnglish: 'The top number in a fraction is the Numerator.',
          },
          {
            id: 'm2',
            topic: 'Fractions and Ratios',
            questionNumber: 2,
            totalQuestions: 3,
            questionMarathi: '1/2 + 1/4 નો સરવાળો કેટલો થાય?',
            questionEnglish: 'What is 1/2 + 1/4 equal to?',
            options: [
              { key: 'A', labelMarathi: '3/4', labelEnglish: '3/4' },
              { key: 'B', labelMarathi: '2/6', labelEnglish: '2/6' },
              { key: 'C', labelMarathi: '2/4', labelEnglish: '2/4' },
              { key: 'D', labelMarathi: '1/8', labelEnglish: '1/8' },
            ],
            correctKey: 'A',
            explanationMarathi: '1/2 ને 2/4 માં ફેરવો, પછી 2/4 + 1/4 = 3/4.',
            explanationEnglish: 'Convert 1/2 to 2/4, then add 2/4 + 1/4 = 3/4.',
          },
          {
            id: 'm3',
            topic: 'Fractions and Ratios',
            questionNumber: 3,
            totalQuestions: 3,
            questionMarathi: 'એક વર્ગમાં 15 છોકરાઓ અને 10 છોકરીઓ છે, તો તેમનો ગુણોત્તર કેટલો થાય?',
            questionEnglish: 'If a class has 15 boys and 10 girls, what is the ratio of boys to girls?',
            options: [
              { key: 'A', labelMarathi: '3:2', labelEnglish: '3:2' },
              { key: 'B', labelMarathi: '2:3', labelEnglish: '2:3' },
              { key: 'C', labelMarathi: '15:10', labelEnglish: '15:10' },
              { key: 'D', labelMarathi: '5:2', labelEnglish: '5:2' },
            ],
            correctKey: 'A',
            explanationMarathi: 'બંને સંખ્યાઓને 5 વડે ભાગતાં 3:2 ગુણોત્તર મળે છે.',
            explanationEnglish: 'Dividing both numbers by 5 gives a 3:2 ratio.',
          },
        ];
      case 'ta':
        return [
          {
            id: 'm1',
            topic: 'Fractions and Ratios',
            questionNumber: 1,
            totalQuestions: 3,
            questionMarathi: '3/4 என்ற பின்னத்தில் 3 என்ற எண் எவ்வாறு அழைக்கப்படுகிறது?',
            questionEnglish: 'In the fraction 3/4, what is the number 3 called?',
            options: [
              { key: 'A', labelMarathi: 'தொகுதி (Numerator)', labelEnglish: 'Numerator' },
              { key: 'B', labelMarathi: 'பகுதி (Denominator)', labelEnglish: 'Denominator' },
              { key: 'C', labelMarathi: 'ஈவு (Quotient)', labelEnglish: 'Quotient' },
              { key: 'D', labelMarathi: 'மீதி (Remainder)', labelEnglish: 'Remainder' },
            ],
            correctKey: 'A',
            explanationMarathi: 'பின்னத்தில் மேலே உள்ள எண் தொகுதி (Numerator) என அழைக்கப்படுகிறது.',
            explanationEnglish: 'The top number in a fraction is the Numerator.',
          },
          {
            id: 'm2',
            topic: 'Fractions and Ratios',
            questionNumber: 2,
            totalQuestions: 3,
            questionMarathi: '1/2 + 1/4 இன் மதிப்பு என்ன?',
            questionEnglish: 'What is 1/2 + 1/4 equal to?',
            options: [
              { key: 'A', labelMarathi: '3/4', labelEnglish: '3/4' },
              { key: 'B', labelMarathi: '2/6', labelEnglish: '2/6' },
              { key: 'C', labelMarathi: '2/4', labelEnglish: '2/4' },
              { key: 'D', labelMarathi: '1/8', labelEnglish: '1/8' },
            ],
            correctKey: 'A',
            explanationMarathi: '1/2 ஐ 2/4 என மாற்றி, 2/4 + 1/4 = 3/4 எனக் கூட்ட வேண்டும்.',
            explanationEnglish: 'Convert 1/2 to 2/4, then add 2/4 + 1/4 = 3/4.',
          },
          {
            id: 'm3',
            topic: 'Fractions and Ratios',
            questionNumber: 3,
            totalQuestions: 3,
            questionMarathi: 'ஒரு வகுப்பில் 15 சிறுவர்களும் 10 சிறுமிகளும் இருந்தால், அவர்களின் விகிதம் என்ன?',
            questionEnglish: 'If a class has 15 boys and 10 girls, what is the ratio of boys to girls?',
            options: [
              { key: 'A', labelMarathi: '3:2', labelEnglish: '3:2' },
              { key: 'B', labelMarathi: '2:3', labelEnglish: '2:3' },
              { key: 'C', labelMarathi: '15:10', labelEnglish: '15:10' },
              { key: 'D', labelMarathi: '5:2', labelEnglish: '5:2' },
            ],
            correctKey: 'A',
            explanationMarathi: 'இரு எண்களையும் 5 ஆல் வகுத்தால் 3:2 என்ற எளிய விகிதம் கிடைக்கும்.',
            explanationEnglish: 'Dividing both numbers by 5 gives a 3:2 ratio.',
          },
        ];
      case 'mr':
      default:
        return [
          {
            id: 'm1',
            topic: 'Fractions and Ratios',
            questionNumber: 1,
            totalQuestions: 3,
            questionMarathi: '३/४ या अपूर्णांकामध्ये ३ या संख्येला काय म्हणतात?',
            questionEnglish: 'In the fraction 3/4, what is the number 3 called?',
            options: [
              { key: 'A', labelMarathi: 'अंश (Numerator)', labelEnglish: 'Numerator' },
              { key: 'B', labelMarathi: 'छेद (Denominator)', labelEnglish: 'Denominator' },
              { key: 'C', labelMarathi: 'भागाकार (Quotient)', labelEnglish: 'Quotient' },
              { key: 'D', labelMarathi: 'बाकी (Remainder)', labelEnglish: 'Remainder' },
            ],
            correctKey: 'A',
            explanationMarathi: 'अपूर्णांकातील वरील संख्येला अंश (Numerator) म्हणतात.',
            explanationEnglish: 'The top number in a fraction is the Numerator.',
          },
          {
            id: 'm2',
            topic: 'Fractions and Ratios',
            questionNumber: 2,
            totalQuestions: 3,
            questionMarathi: '१/२ + १/४ चे उत्तर किती येईल?',
            questionEnglish: 'What is 1/2 + 1/4 equal to?',
            options: [
              { key: 'A', labelMarathi: '३/४', labelEnglish: '3/4' },
              { key: 'B', labelMarathi: '२/६', labelEnglish: '2/6' },
              { key: 'C', labelMarathi: '२/४', labelEnglish: '2/4' },
              { key: 'D', labelMarathi: '१/८', labelEnglish: '1/8' },
            ],
            correctKey: 'A',
            explanationMarathi: '१/२ चा सममूल्य अपूर्णांक २/४ होतो, २/४ + १/४ = ३/४.',
            explanationEnglish: 'Convert 1/2 to 2/4, then add 2/4 + 1/4 = 3/4.',
          },
          {
            id: 'm3',
            topic: 'Fractions and Ratios',
            questionNumber: 3,
            totalQuestions: 3,
            questionMarathi: 'एका वर्गात १५ मुलगे व १० मुली आहेत, तर मुलगे आणि मुलींचे सोपे गुणोत्तर किती?',
            questionEnglish: 'If a class has 15 boys and 10 girls, what is the ratio of boys to girls?',
            options: [
              { key: 'A', labelMarathi: '३:२', labelEnglish: '3:2' },
              { key: 'B', labelMarathi: '२:३', labelEnglish: '2:3' },
              { key: 'C', labelMarathi: '१५:१०', labelEnglish: '15:10' },
              { key: 'D', labelMarathi: '५:२', labelEnglish: '5:2' },
            ],
            correctKey: 'A',
            explanationMarathi: 'दोन्ही संख्यांना ५ ने भागल्यास ३:२ हे सोपे गुणोत्तर मिळते.',
            explanationEnglish: 'Dividing both numbers by 5 gives a 3:2 ratio.',
          },
        ];
    }
  }

  if (subject === 'social_studies') {
    switch (language) {
      case 'en':
        return [
          {
            id: 's1',
            topic: 'Maps and Climate',
            questionNumber: 1,
            totalQuestions: 3,
            questionMarathi: 'What do horizontal lines running East to West on a globe represent?',
            questionEnglish: 'What do horizontal lines running East to West on a globe represent?',
            options: [
              { key: 'A', labelMarathi: 'Parallels of Latitude', labelEnglish: 'Parallels of Latitude' },
              { key: 'B', labelMarathi: 'Meridians of Longitude', labelEnglish: 'Meridians of Longitude' },
              { key: 'C', labelMarathi: 'Equator Only', labelEnglish: 'Equator Only' },
              { key: 'D', labelMarathi: 'Time Zones', labelEnglish: 'Time Zones' },
            ],
            correctKey: 'A',
            explanationMarathi: 'Parallels of latitude run horizontally east to west and measure distance north or south of the Equator.',
            explanationEnglish: 'Parallels of latitude run horizontally east to west and measure distance north or south of the Equator.',
          },
          {
            id: 's2',
            topic: 'Maps and Climate',
            questionNumber: 2,
            totalQuestions: 3,
            questionMarathi: 'Which central latitude line divides the Earth into Northern and Southern Hemispheres?',
            questionEnglish: 'Which central latitude line divides the Earth into Northern and Southern Hemispheres?',
            options: [
              { key: 'A', labelMarathi: 'Prime Meridian', labelEnglish: 'Prime Meridian' },
              { key: 'B', labelMarathi: 'Equator (0°)', labelEnglish: 'Equator (0°)' },
              { key: 'C', labelMarathi: 'Tropic of Cancer', labelEnglish: 'Tropic of Cancer' },
              { key: 'D', labelMarathi: 'Arctic Circle', labelEnglish: 'Arctic Circle' },
            ],
            correctKey: 'B',
            explanationMarathi: 'The Equator at 0° latitude divides Earth equally into Northern and Southern Hemispheres.',
            explanationEnglish: 'The Equator at 0° latitude divides Earth equally into Northern and Southern Hemispheres.',
          },
          {
            id: 's3',
            topic: 'Maps and Climate',
            questionNumber: 3,
            totalQuestions: 3,
            questionMarathi: 'What type of map displays natural features like mountain ranges, rivers, and plateaus?',
            questionEnglish: 'What type of map displays natural features like mountain ranges, rivers, and plateaus?',
            options: [
              { key: 'A', labelMarathi: 'Physical Map', labelEnglish: 'Physical Map' },
              { key: 'B', labelMarathi: 'Political Map', labelEnglish: 'Political Map' },
              { key: 'C', labelMarathi: 'Climate Map', labelEnglish: 'Climate Map' },
              { key: 'D', labelMarathi: 'Road Map', labelEnglish: 'Road Map' },
            ],
            correctKey: 'A',
            explanationMarathi: 'Physical maps show natural landforms and rivers.',
            explanationEnglish: 'Physical maps show natural landforms and rivers.',
          },
        ];
      case 'hi':
        return [
          {
            id: 's1',
            topic: 'Maps and Climate',
            questionNumber: 1,
            totalQuestions: 3,
            questionMarathi: 'ग्लोब पर पूर्व से पश्चिम की ओर खींची गई क्षैतिज रेखाओं को क्या कहा जाता है?',
            questionEnglish: 'What do horizontal lines running East to West on a globe represent?',
            options: [
              { key: 'A', labelMarathi: 'अक्षांश रेखाएँ (Latitude)', labelEnglish: 'Parallels of Latitude' },
              { key: 'B', labelMarathi: 'देशांतर रेखाएँ (Longitude)', labelEnglish: 'Meridians of Longitude' },
              { key: 'C', labelMarathi: 'केवल भूमध्य रेखा', labelEnglish: 'Equator Only' },
              { key: 'D', labelMarathi: 'समय क्षेत्र', labelEnglish: 'Time Zones' },
            ],
            correctKey: 'A',
            explanationMarathi: 'अक्षांश रेखाएँ पूर्व से पश्चिम दिशा में स्थित समानांतर रेखाएँ होती हैं।',
            explanationEnglish: 'Parallels of latitude run horizontally east to west.',
          },
          {
            id: 's2',
            topic: 'Maps and Climate',
            questionNumber: 2,
            totalQuestions: 3,
            questionMarathi: 'पृथ्वी को उत्तरी और दक्षिणी गोलार्ध में विभाजित करने वाली शून्य अंश रेखा कौन सी है?',
            questionEnglish: 'Which central latitude line divides the Earth into Northern and Southern Hemispheres?',
            options: [
              { key: 'A', labelMarathi: 'मुख्य याम्योत्तर', labelEnglish: 'Prime Meridian' },
              { key: 'B', labelMarathi: 'भूमध्य रेखा (0° Equator)', labelEnglish: 'Equator (0°)' },
              { key: 'C', labelMarathi: 'कर्क रेखा', labelEnglish: 'Tropic of Cancer' },
              { key: 'D', labelMarathi: 'मकर रेखा', labelEnglish: 'Tropic of Capricorn' },
            ],
            correctKey: 'B',
            explanationMarathi: '0° भूमध्य रेखा (Equator) पृथ्वी को दो समान गोलार्धों में विभाजित करती है।',
            explanationEnglish: 'The Equator at 0° divides Earth into Northern and Southern Hemispheres.',
          },
          {
            id: 's3',
            topic: 'Maps and Climate',
            questionNumber: 3,
            totalQuestions: 3,
            questionMarathi: 'पर्वत, नदियाँ और पठार जैसी प्राकृतिक आकृतियाँ दर्शाने वाले मानचित्र को क्या कहते हैं?',
            questionEnglish: 'What type of map shows mountain ranges, rivers, and plateaus?',
            options: [
              { key: 'A', labelMarathi: 'भौतिक मानचित्र (Physical Map)', labelEnglish: 'Physical Map' },
              { key: 'B', labelMarathi: 'राजनीतिक मानचित्र', labelEnglish: 'Political Map' },
              { key: 'C', labelMarathi: 'जलवायु मानचित्र', labelEnglish: 'Climate Map' },
              { key: 'D', labelMarathi: 'सड़क मानचित्र', labelEnglish: 'Road Map' },
            ],
            correctKey: 'A',
            explanationMarathi: 'भौतिक मानचित्र में प्राकृतिक भू-आकृतियों जैसे पर्वत, नदियाँ आदि को दर्शाया जाता है।',
            explanationEnglish: 'Physical maps display natural landforms.',
          },
        ];
      case 'gu':
        return [
          {
            id: 's1',
            topic: 'Maps and Climate',
            questionNumber: 1,
            totalQuestions: 3,
            questionMarathi: 'પૃથ્વીના ગોળા પર પૂર્વથી પશ્ચિમ દોરેલી આડી રેખાઓને શું કહેવાય?',
            questionEnglish: 'What do horizontal lines running East to West on a globe represent?',
            options: [
              { key: 'A', labelMarathi: 'અક્ષાંશવૃત્ત (Latitude)', labelEnglish: 'Parallels of Latitude' },
              { key: 'B', labelMarathi: 'રેખાંશવૃત્ત (Longitude)', labelEnglish: 'Meridians of Longitude' },
              { key: 'C', labelMarathi: 'માત્ર વિષુવવૃત્ત', labelEnglish: 'Equator Only' },
              { key: 'D', labelMarathi: 'સમય ઝોન', labelEnglish: 'Time Zones' },
            ],
            correctKey: 'A',
            explanationMarathi: 'અક્ષાંશવૃત્ત (Latitude) પૃથ્વી પર પૂર્વથી પશ્ચિમ આડી દોરેલી કાલ્પનિક રેખાઓ છે.',
            explanationEnglish: 'Parallels of latitude run horizontally east to west.',
          },
          {
            id: 's2',
            topic: 'Maps and Climate',
            questionNumber: 2,
            totalQuestions: 3,
            questionMarathi: 'પૃથ્વીને ઉત્તર અને દક્ષિણ ગોળાર્ધમાં વહેંચતી 0° રેખા કઈ છે?',
            questionEnglish: 'Which central latitude line divides the Earth into Northern and Southern Hemispheres?',
            options: [
              { key: 'A', labelMarathi: 'મુખ્ય રેખાંશવૃત્ત', labelEnglish: 'Prime Meridian' },
              { key: 'B', labelMarathi: 'વિષુવવૃત્ત (0° Equator)', labelEnglish: 'Equator (0°)' },
              { key: 'C', labelMarathi: 'કર્કવૃત્ત', labelEnglish: 'Tropic of Cancer' },
              { key: 'D', labelMarathi: 'મકરવૃત્ત', labelEnglish: 'Tropic of Capricorn' },
            ],
            correctKey: 'B',
            explanationMarathi: '0° વિષુવવૃત્ત (Equator) પૃથ્વીને બે સરખા ભાગોમાં વહેંચે છે.',
            explanationEnglish: 'The Equator at 0° divides Earth into Northern and Southern Hemispheres.',
          },
          {
            id: 's3',
            topic: 'Maps and Climate',
            questionNumber: 3,
            totalQuestions: 3,
            questionMarathi: 'પર્વતો, નદીઓ અને ઉચ્ચ પ્રદેશો દર્શાવતા નકશાને શું કહે છે?',
            questionEnglish: 'What type of map shows mountains, rivers, and plateaus?',
            options: [
              { key: 'A', labelMarathi: 'પ્રાકૃતિક નકશો (Physical Map)', labelEnglish: 'Physical Map' },
              { key: 'B', labelMarathi: 'રાષ્ટ્રીય/રાજકીય નકશો', labelEnglish: 'Political Map' },
              { key: 'C', labelMarathi: 'આબોહવા નકશો', labelEnglish: 'Climate Map' },
              { key: 'D', labelMarathi: 'માર્ગ નકશો', labelEnglish: 'Road Map' },
            ],
            correctKey: 'A',
            explanationMarathi: 'પ્રાકૃતિક નકશામાં કુદરતી ભૂ-આકારો અને નદીઓ દર્શાવવામાં આવે છે.',
            explanationEnglish: 'Physical maps display natural landforms.',
          },
        ];
      case 'ta':
        return [
          {
            id: 's1',
            topic: 'Maps and Climate',
            questionNumber: 1,
            totalQuestions: 3,
            questionMarathi: 'புவியின் மீது கிழக்கிலிருந்து மேற்காகச் செல்லும் கிடைமட்டக் கோடுகள் எவ்வாறு அழைக்கப்படுகின்றன?',
            questionEnglish: 'What do horizontal lines running East to West on a globe represent?',
            options: [
              { key: 'A', labelMarathi: 'அட்சரேகைகள் (Latitude)', labelEnglish: 'Parallels of Latitude' },
              { key: 'B', labelMarathi: 'தீர்க்கரேகைகள் (Longitude)', labelEnglish: 'Meridians of Longitude' },
              { key: 'C', labelMarathi: 'பூமத்திய ரேகை மட்டும்', labelEnglish: 'Equator Only' },
              { key: 'D', labelMarathi: 'நேர மண்டலங்கள்', labelEnglish: 'Time Zones' },
            ],
            correctKey: 'A',
            explanationMarathi: 'அட்சரேகைகள் (Latitude) கிழக்கிலிருந்து மேற்காக இணையான கோடுகளாகச் செல்கின்றன.',
            explanationEnglish: 'Parallels of latitude run horizontally east to west.',
          },
          {
            id: 's2',
            topic: 'Maps and Climate',
            questionNumber: 2,
            totalQuestions: 3,
            questionMarathi: 'பூமியை வடக்கு மற்றும் தெற்கு அரைக்கோளங்களாகப் பிரிக்கும் மத்திய ரேகை எது?',
            questionEnglish: 'Which central latitude line divides the Earth into Northern and Southern Hemispheres?',
            options: [
              { key: 'A', labelMarathi: 'முதன்மை தீர்க்கரேகை', labelEnglish: 'Prime Meridian' },
              { key: 'B', labelMarathi: 'பூமத்திய ரேகை (0° Equator)', labelEnglish: 'Equator (0°)' },
              { key: 'C', labelMarathi: 'கடக ரேகை', labelEnglish: 'Tropic of Cancer' },
              { key: 'D', labelMarathi: 'மகர ரேகை', labelEnglish: 'Tropic of Capricorn' },
            ],
            correctKey: 'B',
            explanationMarathi: '0° பூமத்திய ரேகை (Equator) பூமியை இரு சம அரைக்கோளங்களாகப் பிரிக்கிறது.',
            explanationEnglish: 'The Equator at 0° divides Earth into Northern and Southern Hemispheres.',
          },
          {
            id: 's3',
            topic: 'Maps and Climate',
            questionNumber: 3,
            totalQuestions: 3,
            questionMarathi: 'மலைகள், ஆறுகள் மற்றும் பீடபூமிகளைக் காட்டும் வரைபடம் எது?',
            questionEnglish: 'What type of map shows mountains, rivers, and plateaus?',
            options: [
              { key: 'A', labelMarathi: 'இயற்கை அமைப்பு வரைபடம் (Physical Map)', labelEnglish: 'Physical Map' },
              { key: 'B', labelMarathi: 'அரசியல் வரைபடம்', labelEnglish: 'Political Map' },
              { key: 'C', labelMarathi: 'காலநிலை வரைபடம்', labelEnglish: 'Climate Map' },
              { key: 'D', labelMarathi: 'சாலை வரைபடம்', labelEnglish: 'Road Map' },
            ],
            correctKey: 'A',
            explanationMarathi: 'இயற்கை அமைப்பு வரைபடம் நிலப்பரப்புகள் மற்றும் நீர்நிலைகளைக் காட்டுகிறது.',
            explanationEnglish: 'Physical maps display natural landforms.',
          },
        ];
      case 'mr':
      default:
        return [
          {
            id: 's1',
            topic: 'Maps and Climate',
            questionNumber: 1,
            totalQuestions: 3,
            questionMarathi: 'पृथ्वीच्या गोलावर पूर्वेकडून पश्चिमेकडे जाणाऱ्या आडव्या रेषांना काय म्हणतात?',
            questionEnglish: 'What do horizontal lines running East to West on a globe represent?',
            options: [
              { key: 'A', labelMarathi: 'अक्षवृत्ते (Latitude)', labelEnglish: 'Parallels of Latitude' },
              { key: 'B', labelMarathi: 'रेखावृत्ते (Longitude)', labelEnglish: 'Meridians of Longitude' },
              { key: 'C', labelMarathi: 'केवळ विषुववृत्त', labelEnglish: 'Equator Only' },
              { key: 'D', labelMarathi: 'वेळ पट्टे', labelEnglish: 'Time Zones' },
            ],
            correctKey: 'A',
            explanationMarathi: 'अक्षवृत्ते (Latitude) ही विषुववृत्ताला समांतर असणारी आडवी वर्तुळे असतात.',
            explanationEnglish: 'Parallels of latitude run horizontally east to west.',
          },
          {
            id: 's2',
            topic: 'Maps and Climate',
            questionNumber: 2,
            totalQuestions: 3,
            questionMarathi: 'पृथ्वीचे उत्तर आणि दक्षिण गोलार्धात समान भाग करणारी काल्पनिक रेषा कोणती?',
            questionEnglish: 'Which central latitude line divides the Earth into Northern and Southern Hemispheres?',
            options: [
              { key: 'A', labelMarathi: 'मूळ रेखावृत्त', labelEnglish: 'Prime Meridian' },
              { key: 'B', labelMarathi: 'विषुववृत्त (0° Equator)', labelEnglish: 'Equator (0°)' },
              { key: 'C', labelMarathi: 'कर्कवृत्त', labelEnglish: 'Tropic of Cancer' },
              { key: 'D', labelMarathi: 'मकरवृत्त', labelEnglish: 'Tropic of Capricorn' },
            ],
            correctKey: 'B',
            explanationMarathi: '०° विषुववृत्त (Equator) पृथ्वीला उत्तर आणि दक्षिण गोलार्धात विभागते.',
            explanationEnglish: 'The Equator at 0° divides Earth into Northern and Southern Hemispheres.',
          },
          {
            id: 's3',
            topic: 'Maps and Climate',
            questionNumber: 3,
            totalQuestions: 3,
            questionMarathi: 'पर्वत, नद्या, पठारे आणि प्राकृतिक रचना दाखवणाऱ्या नकाशाला काय म्हणतात?',
            questionEnglish: 'What type of map shows mountains, rivers, and plateaus?',
            options: [
              { key: 'A', labelMarathi: 'प्राकृतिक नकाशा (Physical Map)', labelEnglish: 'Physical Map' },
              { key: 'B', labelMarathi: 'राजकीय नकाशा', labelEnglish: 'Political Map' },
              { key: 'C', labelMarathi: 'हवामान नकाशा', labelEnglish: 'Climate Map' },
              { key: 'D', labelMarathi: 'रस्ता नकाशा', labelEnglish: 'Road Map' },
            ],
            correctKey: 'A',
            explanationMarathi: 'प्राकृतिक नकाशात (Physical Map) डोंगर, नद्या आणि प्राकृतिक भूरूपे दर्शवली जातात.',
            explanationEnglish: 'Physical maps display natural landforms.',
          },
        ];
    }
  }

  // Default to Science (Photosynthesis)
  switch (language) {
    case 'en':
      return [
        {
          id: 'q1',
          topic: 'Photosynthesis',
          questionNumber: 1,
          totalQuestions: 3,
          questionMarathi: 'What do green plants use during photosynthesis to prepare their food?',
          questionEnglish: 'What do green plants use during photosynthesis to prepare their food?',
          options: [
            { key: 'A', labelMarathi: 'Sunlight, Water & CO₂', labelEnglish: 'Sunlight, Water & CO₂' },
            { key: 'B', labelMarathi: 'Soil Only', labelEnglish: 'Soil Only' },
            { key: 'C', labelMarathi: 'Wind & Sound', labelEnglish: 'Wind & Sound' },
            { key: 'D', labelMarathi: 'Plastic & Chemicals', labelEnglish: 'Plastic & Chemicals' },
          ],
          correctKey: 'A',
          explanationMarathi: 'Plants use sunlight, water, and carbon dioxide to produce glucose (food) and oxygen.',
          explanationEnglish: 'Plants use sunlight, water, and carbon dioxide to produce glucose (food) and oxygen.',
        },
        {
          id: 'q2',
          topic: 'Photosynthesis',
          questionNumber: 2,
          totalQuestions: 3,
          questionMarathi: 'Which green pigment in leaves absorbs solar energy for photosynthesis?',
          questionEnglish: 'Which green pigment in leaves absorbs solar energy for photosynthesis?',
          options: [
            { key: 'A', labelMarathi: 'Water', labelEnglish: 'Water' },
            { key: 'B', labelMarathi: 'Chlorophyll', labelEnglish: 'Chlorophyll' },
            { key: 'C', labelMarathi: 'Oxygen', labelEnglish: 'Oxygen' },
            { key: 'D', labelMarathi: 'Nitrogen', labelEnglish: 'Nitrogen' },
          ],
          correctKey: 'B',
          explanationMarathi: 'Chlorophyll is the green pigment in plant leaves that absorbs solar energy.',
          explanationEnglish: 'Chlorophyll is the green pigment in plant leaves that absorbs solar energy.',
        },
        {
          id: 'q3',
          topic: 'Plant Cells',
          questionNumber: 3,
          totalQuestions: 3,
          questionMarathi: 'Which protective outer structure is present in plant cells but absent in animal cells?',
          questionEnglish: 'Which protective outer structure is present in plant cells but absent in animal cells?',
          options: [
            { key: 'A', labelMarathi: 'Cell Wall', labelEnglish: 'Cell Wall' },
            { key: 'B', labelMarathi: 'Nucleus', labelEnglish: 'Nucleus' },
            { key: 'C', labelMarathi: 'Mitochondria', labelEnglish: 'Mitochondria' },
            { key: 'D', labelMarathi: 'Cytoplasm', labelEnglish: 'Cytoplasm' },
          ],
          correctKey: 'A',
          explanationMarathi: 'The cell wall provides rigid structure and protection to plant cells.',
          explanationEnglish: 'The cell wall provides rigid structure and protection to plant cells.',
        },
      ];
    case 'hi':
      return [
        {
          id: 'q1',
          topic: 'Photosynthesis',
          questionNumber: 1,
          totalQuestions: 3,
          questionMarathi: 'पौधे अपना भोजन बनाने के लिए मुख्य रूप से किसका उपयोग करते हैं?',
          questionEnglish: 'What do plants use to make food during photosynthesis?',
          options: [
            { key: 'A', labelMarathi: 'सूर्य का प्रकाश, जल और CO₂', labelEnglish: 'Sunlight, Water & CO₂' },
            { key: 'B', labelMarathi: 'केवल मिट्टी', labelEnglish: 'Soil Only' },
            { key: 'C', labelMarathi: 'हवा और ध्वनि', labelEnglish: 'Wind & Sound' },
            { key: 'D', labelMarathi: 'प्लास्टिक', labelEnglish: 'Plastic' },
          ],
          correctKey: 'A',
          explanationMarathi: 'पौधे सूर्य के प्रकाश, जल और कार्बन डाइऑक्साइड का उपयोग करके ग्लूकोज बनाते हैं।',
          explanationEnglish: 'Plants use sunlight, water, and CO₂ to produce glucose.',
        },
        {
          id: 'q2',
          topic: 'Photosynthesis',
          questionNumber: 2,
          totalQuestions: 3,
          questionMarathi: 'पत्तियों को हरा रंग देने वाला और सौर ऊर्जा अवशोषित करने वाला वर्णक कौन सा है?',
          questionEnglish: 'Which pigment gives leaves their green color?',
          options: [
            { key: 'A', labelMarathi: 'जल', labelEnglish: 'Water' },
            { key: 'B', labelMarathi: 'क्लोरोफिल (Chlorophyll)', labelEnglish: 'Chlorophyll' },
            { key: 'C', labelMarathi: 'ऑक्सीजन', labelEnglish: 'Oxygen' },
            { key: 'D', labelMarathi: 'नाइट्रोजन', labelEnglish: 'Nitrogen' },
          ],
          correctKey: 'B',
          explanationMarathi: 'क्लोरोफिल पत्तियों में मौजूद हरा वर्णक है जो प्रकाश संश्लेषण के लिए सूर्य का प्रकाश अवशोषित करता है।',
          explanationEnglish: 'Chlorophyll is the green pigment in leaves.',
        },
        {
          id: 'q3',
          topic: 'Plant Cells',
          questionNumber: 3,
          totalQuestions: 3,
          questionMarathi: 'पादप कोशिकाओं को संरचनात्मक मजबूती प्रदान करने वाली बाहरी दीवार कौन सी है?',
          questionEnglish: 'Which outer wall is present in plant cells but absent in animal cells?',
          options: [
            { key: 'A', labelMarathi: 'कोशिका भित्ति (Cell Wall)', labelEnglish: 'Cell Wall' },
            { key: 'B', labelMarathi: 'केंद्रक (Nucleus)', labelEnglish: 'Nucleus' },
            { key: 'C', labelMarathi: 'माइटोकॉन्ड्रिया', labelEnglish: 'Mitochondria' },
            { key: 'D', labelMarathi: 'कोशिका द्रव्य', labelEnglish: 'Cytoplasm' },
          ],
          correctKey: 'A',
          explanationMarathi: 'कोशिका भित्ति (Cell Wall) पादप कोशिका को आकार और सुरक्षा प्रदान करती है।',
          explanationEnglish: 'The cell wall provides structure to plant cells.',
        },
      ];
    case 'gu':
      return [
        {
          id: 'q1',
          topic: 'Photosynthesis',
          questionNumber: 1,
          totalQuestions: 3,
          questionMarathi: 'વનસ્પતિ પોતાનો ખોરાક બનાવવા માટે મુખ્યત્વે શાનો ઉપયોગ કરે છે?',
          questionEnglish: 'What do plants use to make food during photosynthesis?',
          options: [
            { key: 'A', labelMarathi: 'સૂર્યપ્રકાશ, પાણી અને CO₂', labelEnglish: 'Sunlight, Water & CO₂' },
            { key: 'B', labelMarathi: 'માત્ર માટી', labelEnglish: 'Soil Only' },
            { key: 'C', labelMarathi: 'પવન અને અવાજ', labelEnglish: 'Wind & Sound' },
            { key: 'D', labelMarathi: 'પ્લાસ્ટિક', labelEnglish: 'Plastic' },
          ],
          correctKey: 'A',
          explanationMarathi: 'વનસ્પતિ સૂર્યપ્રકાશ, પાણી અને કાર્બન ડાયોક્સાઇડનો ઉપયોગ કરીને ગ્લુકોઝ બનાવે છે.',
          explanationEnglish: 'Plants use sunlight, water, and CO₂ to produce glucose.',
        },
        {
          id: 'q2',
          topic: 'Photosynthesis',
          questionNumber: 2,
          totalQuestions: 3,
          questionMarathi: 'પાનને લીલો રંગ આપનાર અને સૂર્યપ્રકાશ શોષી લેનાર દ્રવ્ય કયું છે?',
          questionEnglish: 'Which pigment gives leaves their green color?',
          options: [
            { key: 'A', labelMarathi: 'પાણી', labelEnglish: 'Water' },
            { key: 'B', labelMarathi: 'હરિતદ્રવ્ય (Chlorophyll)', labelEnglish: 'Chlorophyll' },
            { key: 'C', labelMarathi: 'ઓક્સિજન', labelEnglish: 'Oxygen' },
            { key: 'D', labelMarathi: 'નાઇટ્રોજન', labelEnglish: 'Nitrogen' },
          ],
          correctKey: 'B',
          explanationMarathi: 'હરિતદ્રવ્ય (Chlorophyll) પાંદડામાં રહેલું લીલું દ્રવ્ય છે જે સૂર્યપ્રકાશ શોષી લે છે.',
          explanationEnglish: 'Chlorophyll absorbs sunlight for photosynthesis.',
        },
        {
          id: 'q3',
          topic: 'Plant Cells',
          questionNumber: 3,
          totalQuestions: 3,
          questionMarathi: 'વનસ્પતિ કોષને મજબૂત આકાર આપતી બહારની દીવાલ કઈ છે?',
          questionEnglish: 'Which outer wall is present in plant cells but absent in animal cells?',
          options: [
            { key: 'A', labelMarathi: 'કોષદીવાલ (Cell Wall)', labelEnglish: 'Cell Wall' },
            { key: 'B', labelMarathi: 'કોષકેન્દ્ર (Nucleus)', labelEnglish: 'Nucleus' },
            { key: 'C', labelMarathi: 'કણાભસૂત્ર', labelEnglish: 'Mitochondria' },
            { key: 'D', labelMarathi: 'કોષરસ', labelEnglish: 'Cytoplasm' },
          ],
          correctKey: 'A',
          explanationMarathi: 'કોષદીવાલ (Cell Wall) વનસ્પતિ કોષને મજબૂતાઈ અને રક્ષણ આપે છે.',
          explanationEnglish: 'The cell wall provides structure to plant cells.',
        },
      ];
    case 'ta':
      return [
        {
          id: 'q1',
          topic: 'Photosynthesis',
          questionNumber: 1,
          totalQuestions: 3,
          questionMarathi: 'தாவரங்கள் உணவு தயாரிக்க முக்கியமாக எதைப் பயன்படுத்துகின்றன?',
          questionEnglish: 'What do plants use to make food during photosynthesis?',
          options: [
            { key: 'A', labelMarathi: 'சூரிய ஒளி, நீர் & CO₂', labelEnglish: 'Sunlight, Water & CO₂' },
            { key: 'B', labelMarathi: 'மண் மட்டும்', labelEnglish: 'Soil Only' },
            { key: 'C', labelMarathi: 'காற்றுக் & ஒலி', labelEnglish: 'Wind & Sound' },
            { key: 'D', labelMarathi: 'பிளாஸ்டிக்', labelEnglish: 'Plastic' },
          ],
          correctKey: 'A',
          explanationMarathi: 'தாவரங்கள் சூரிய ஒளி, நீர் மற்றும் கார்பன் டை ஆக்சைடைப் பயன்படுத்தி உணவை தயாரிக்கின்றன.',
          explanationEnglish: 'Plants use sunlight, water, and CO₂ to produce glucose.',
        },
        {
          id: 'q2',
          topic: 'Photosynthesis',
          questionNumber: 2,
          totalQuestions: 3,
          questionMarathi: 'இலைகளுக்கு பச்சை நிறத்தை அளித்து சூரிய ஒளியை உறிஞ்சும் நிறமி எது?',
          questionEnglish: 'Which pigment gives leaves their green color?',
          options: [
            { key: 'A', labelMarathi: 'நீர்', labelEnglish: 'Water' },
            { key: 'B', labelMarathi: 'பச்சையம் (Chlorophyll)', labelEnglish: 'Chlorophyll' },
            { key: 'C', labelMarathi: 'ஆக்சிஜன்', labelEnglish: 'Oxygen' },
            { key: 'D', labelMarathi: 'நைட்ரஜன்', labelEnglish: 'Nitrogen' },
          ],
          correctKey: 'B',
          explanationMarathi: 'பச்சையம் (Chlorophyll) இலைகளில் சூரிய ஒளியை உறிஞ்சும் பச்சை நிறமியாகும்.',
          explanationEnglish: 'Chlorophyll is the green pigment in leaves.',
        },
        {
          id: 'q3',
          topic: 'Plant Cells',
          questionNumber: 3,
          totalQuestions: 3,
          questionMarathi: 'தாவர செல்லிற்கு அமைப்பை வழங்கும் வெளிச்சுவர் எது?',
          questionEnglish: 'Which outer wall is present in plant cells but absent in animal cells?',
          options: [
            { key: 'A', labelMarathi: 'செல் சுவர் (Cell Wall)', labelEnglish: 'Cell Wall' },
            { key: 'B', labelMarathi: 'உட்கரு (Nucleus)', labelEnglish: 'Nucleus' },
            { key: 'C', labelMarathi: 'மைட்டோகாண்ட்ரியா', labelEnglish: 'Mitochondria' },
            { key: 'D', labelMarathi: 'சைட்டோபிளாசம்', labelEnglish: 'Cytoplasm' },
          ],
          correctKey: 'A',
          explanationMarathi: 'செல் சுவர் (Cell Wall) தாவர செல்களுக்கு பாதுகாப்பையும் உறுதியையும் அளிக்கிறது.',
          explanationEnglish: 'The cell wall provides support to plant cells.',
        },
      ];
    case 'mr':
    default:
      return [
        {
          id: 'q1',
          topic: 'Photosynthesis',
          questionNumber: 1,
          totalQuestions: 3,
          questionMarathi: 'वनस्पती अन्न तयार करण्यासाठी कशाचा वापर करतात?',
          questionEnglish: 'What do plants use to make food?',
          options: [
            { key: 'A', labelMarathi: 'सूर्यप्रकाश व पाणी', labelEnglish: 'Sunlight & Water' },
            { key: 'B', labelMarathi: 'केवळ माती', labelEnglish: 'Soil Only' },
            { key: 'C', labelMarathi: 'वारा व ध्वनी', labelEnglish: 'Wind & Sound' },
            { key: 'D', labelMarathi: 'प्लास्टिक', labelEnglish: 'Plastic' },
          ],
          correctKey: 'A',
          explanationMarathi: 'वनस्पती सूर्यप्रकाश, पाणी आणि कार्बन डायऑक्साइड वापरून स्वतःचे अन्न (ग्लुकोज) तयार करतात.',
          explanationEnglish: 'Plants use sunlight, water, and carbon dioxide to produce glucose (food) during photosynthesis.',
        },
        {
          id: 'q2',
          topic: 'Photosynthesis',
          questionNumber: 2,
          totalQuestions: 3,
          questionMarathi: 'पानांना हिरवा रंग देणारे घटक कोणते?',
          questionEnglish: 'Which pigment gives leaves their green color?',
          options: [
            { key: 'A', labelMarathi: 'पाणी', labelEnglish: 'Water' },
            { key: 'B', labelMarathi: 'हरितद्रव्य (Chlorophyll)', labelEnglish: 'Chlorophyll' },
            { key: 'C', labelMarathi: 'ऑक्सिजन', labelEnglish: 'Oxygen' },
            { key: 'D', labelMarathi: 'नायट्रोजन', labelEnglish: 'Nitrogen' },
          ],
          correctKey: 'B',
          explanationMarathi: 'हरितद्रव्य (Chlorophyll) हा पानांमधील हिरवा रंगकण आहे जो सूर्यप्रकाश शोषून घेतो.',
          explanationEnglish: 'Chlorophyll is the green pigment in leaves that absorbs solar energy.',
        },
        {
          id: 'q3',
          topic: 'Plant Cells',
          questionNumber: 3,
          totalQuestions: 3,
          questionMarathi: 'वनस्पती पेशींमध्ये कोणती बाह्य भिंत असते जी प्राण्यांच्या पेशींमध्ये नसते?',
          questionEnglish: 'Which outer wall is present in plant cells but absent in animal cells?',
          options: [
            { key: 'A', labelMarathi: 'पेशीभित्तिका (Cell Wall)', labelEnglish: 'Cell Wall' },
            { key: 'B', labelMarathi: 'केंद्रक (Nucleus)', labelEnglish: 'Nucleus' },
            { key: 'C', labelMarathi: 'मायटोकॉन्ड्रिया', labelEnglish: 'Mitochondria' },
            { key: 'D', labelMarathi: 'पेशीद्रव्य (Cytoplasm)', labelEnglish: 'Cytoplasm' },
          ],
          correctKey: 'A',
          explanationMarathi: 'पेशीभित्तिका (Cell Wall) वनस्पती पेशीला आकार आणि संरक्षण देते.',
          explanationEnglish: 'The cell wall provides structure and support to plant cells.',
        },
      ];
  }
}
